### PR TITLE
Fix copying engine files (based on #153)

### PR DESCRIPTION
**Pull request by mre**
Might be a fix for https://github.com/tinysearch/tinysearch/issues/152, https://github.com/tinysearch/tinysearch/issues/151, https://github.com/tinysearch/tinysearch/issues/147.
Would be delighted if someone could test this.

### CODE REVIEW

**Comment by mre** [comment]
All credits go to [shijunti19](https://github.com/shijunti19).

**Comment by robinDotDev** [comment]
I am not experienced in working with Rust and Cargo, but I have tested it the following way on macOS 12.2.1 with cargo 1.59.0 and rust 1.56.1 and it worked.

ts-pr154-1
ts-pr-154-2
ts-pr-154-3

Hope this helps.

**Comment by mre** [comment]
Alright! I'll go ahead and merge this then. This is the feedback I was hoping for. Thanks a lot @robinDotDev. 🥳

**Comment by robinDotDev** [comment]
Copy. It is due to the Docker Image build, if I am right? Unfortunately I am not experienced with Docker in order to evaluate this issue.

**Comment by ardeaf** [comment]
Any updates and any way I can help with this?

**Comment by mre** [comment]
The issue should be resolved and the CI build is green again. Are there still any problems?

**Comment by ardeaf** [comment]
> The issue should be resolved and the CI build is green again. Are there still any problems?

I thought I was having issues but it was just with the version on crates.io. When I specified to install from git, it works flawlessly.

**Comment by mre** [comment]
Oh. Published 0.6.4 with the fix to crates.io.

**Pull request merged**
